/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectogestion.vista;
import proyectogestion.logica.ProgramaGestion;
import proyectogestion.modelo.Estudiante;
import javax.swing.JOptionPane;
import proyectogestion.excepciones.EstudianteNoEncontradoException;
import proyectogestion.excepciones.BecaNoEncontradaException;

/**
 *
 * @author fransantana
 */
public class Interfaz extends javax.swing.JFrame {
    private ProgramaGestion programaGestion;

    /**
     * Creates new form Interfaz
     */
    public Interfaz(ProgramaGestion programaGestion) {
        initComponents();
        this.programaGestion = programaGestion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanePrincipal = new javax.swing.JTabbedPane();
        panelRegistrarEstudiante = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtDireccionHogar = new javax.swing.JTextField();
        txtDireccionEstadia = new javax.swing.JTextField();
        txtPorcentajeRSH = new javax.swing.JTextField();
        txtNivelDeportividad = new javax.swing.JTextField();
        txtIngresosFamiliares = new javax.swing.JTextField();
        txtPromedioNotas = new javax.swing.JTextField();
        panelPostularBeca = new javax.swing.JPanel();
        txtRutPostulacion = new javax.swing.JTextField();
        txtCodigoBeca = new javax.swing.JTextField();
        btnPostular = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelBuscarEstudiante = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtRutBuscar = new javax.swing.JTextField();
        btnBuscarEstudiante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEstudiante = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        panelConsultaEstudiante = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar estudiante");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Edad:");

        jLabel3.setText("RUT: ");

        jLabel4.setText("Sexo:");

        jLabel5.setText("Dirección hogar:");

        jLabel6.setText("Dirección estadía:");

        jLabel7.setText("Porcentaje RSH:");

        jLabel8.setText("Nivel deportividad:");

        jLabel9.setText("Ingresos familiares:    ");

        jLabel10.setText("Promedio notas:");

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });

        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });

        txtDireccionHogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionHogarActionPerformed(evt);
            }
        });

        txtDireccionEstadia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionEstadiaActionPerformed(evt);
            }
        });

        txtIngresosFamiliares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresosFamiliaresActionPerformed(evt);
            }
        });

        txtPromedioNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPromedioNotasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistrarEstudianteLayout = new javax.swing.GroupLayout(panelRegistrarEstudiante);
        panelRegistrarEstudiante.setLayout(panelRegistrarEstudianteLayout);
        panelRegistrarEstudianteLayout.setHorizontalGroup(
            panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarEstudianteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarEstudianteLayout.createSequentialGroup()
                        .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41)
                        .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(txtDireccionHogar))))
                    .addGroup(panelRegistrarEstudianteLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnRegistrar))
                    .addGroup(panelRegistrarEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(40, 40, 40)
                        .addComponent(txtPromedioNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(panelRegistrarEstudianteLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(40, 40, 40)
                        .addComponent(txtPorcentajeRSH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegistrarEstudianteLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(30, 30, 30)
                            .addComponent(txtDireccionEstadia))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegistrarEstudianteLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(24, 24, 24)
                            .addComponent(txtNivelDeportividad))
                        .addGroup(panelRegistrarEstudianteLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIngresosFamiliares, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegistrarEstudianteLayout.setVerticalGroup(
            panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarEstudianteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccionHogar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDireccionEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPromedioNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNivelDeportividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorcentajeRSH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelRegistrarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIngresosFamiliares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(23, 23, 23))
        );

        tabbedPanePrincipal.addTab("Registro Estudiante", panelRegistrarEstudiante);

        txtCodigoBeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBecaActionPerformed(evt);
            }
        });

        btnPostular.setText("Postular");
        btnPostular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostularActionPerformed(evt);
            }
        });

        jLabel11.setText("RUT estudiante:");

        jLabel12.setText("Código beca:");

        javax.swing.GroupLayout panelPostularBecaLayout = new javax.swing.GroupLayout(panelPostularBeca);
        panelPostularBeca.setLayout(panelPostularBecaLayout);
        panelPostularBecaLayout.setHorizontalGroup(
            panelPostularBecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPostularBecaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelPostularBecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(27, 27, 27)
                .addGroup(panelPostularBecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRutPostulacion)
                    .addComponent(txtCodigoBeca)
                    .addComponent(btnPostular, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPostularBecaLayout.setVerticalGroup(
            panelPostularBecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPostularBecaLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(panelPostularBecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtRutPostulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelPostularBecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCodigoBeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnPostular)
                .addContainerGap(412, Short.MAX_VALUE))
        );

        tabbedPanePrincipal.addTab("Postulación", panelPostularBeca);

        jLabel13.setText("RUT del estudiante:");

        txtRutBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutBuscarActionPerformed(evt);
            }
        });

        btnBuscarEstudiante.setText("Buscar");
        btnBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstudianteActionPerformed(evt);
            }
        });

        txtAreaEstudiante.setEditable(false);
        txtAreaEstudiante.setColumns(20);
        txtAreaEstudiante.setRows(5);
        jScrollPane1.setViewportView(txtAreaEstudiante);

        jLabel14.setText("Datos del estudiante:");

        javax.swing.GroupLayout panelBuscarEstudianteLayout = new javax.swing.GroupLayout(panelBuscarEstudiante);
        panelBuscarEstudiante.setLayout(panelBuscarEstudianteLayout);
        panelBuscarEstudianteLayout.setHorizontalGroup(
            panelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarEstudianteLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(panelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBuscarEstudianteLayout.createSequentialGroup()
                        .addGroup(panelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(40, 40, 40)
                        .addComponent(txtRutBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnBuscarEstudiante)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        panelBuscarEstudianteLayout.setVerticalGroup(
            panelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarEstudianteLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(panelBuscarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEstudiante)
                    .addComponent(jLabel13))
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        tabbedPanePrincipal.addTab("Busqueda", panelBuscarEstudiante);

        jLabel15.setText("jLabel15");

        javax.swing.GroupLayout panelConsultaEstudianteLayout = new javax.swing.GroupLayout(panelConsultaEstudiante);
        panelConsultaEstudiante.setLayout(panelConsultaEstudianteLayout);
        panelConsultaEstudianteLayout.setHorizontalGroup(
            panelConsultaEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaEstudianteLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel15)
                .addContainerGap(517, Short.MAX_VALUE))
        );
        panelConsultaEstudianteLayout.setVerticalGroup(
            panelConsultaEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaEstudianteLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel15)
                .addContainerGap(547, Short.MAX_VALUE))
        );

        tabbedPanePrincipal.addTab("Consulta", panelConsultaEstudiante);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1534, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
        String nombre = txtNombre.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        String rut = txtRut.getText().trim();
        String sexo = txtSexo.getText();
        String direccionHogar = txtDireccionHogar.getText();
        String direccionEstadia = txtDireccionEstadia.getText();

        double porcentajeRSH = Double.parseDouble(txtPorcentajeRSH.getText());

        int nivelDeportividad = Integer.parseInt(txtNivelDeportividad.getText());

        int ingresosFamiliares = Integer.parseInt(txtIngresosFamiliares.getText());

        double promedioNotas = Double.parseDouble(txtPromedioNotas.getText());

        Estudiante estudiante = new Estudiante(
            nombre,
            edad,
            rut,
            sexo,
            direccionHogar,
            direccionEstadia,
            porcentajeRSH,
            nivelDeportividad,
            ingresosFamiliares,
            promedioNotas
        );

        programaGestion.registrarEstudiante(estudiante);

        JOptionPane.showMessageDialog( this, "Estudiante registrado correctamente." );
        limpiarCamposRegistro();
        
        } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
            this,
            "Revisa los datos numéricos ingresados.",
            "Error de datos",
            JOptionPane.ERROR_MESSAGE
        );
        }
    
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void txtIngresosFamiliaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresosFamiliaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresosFamiliaresActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtCodigoBecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBecaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCodigoBecaActionPerformed

    private void btnPostularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostularActionPerformed
        // TODO add your handling code here:
        try {
            String rut = txtRutPostulacion.getText().trim();
            int codigoBeca = Integer.parseInt(txtCodigoBeca.getText());

            boolean resultado = programaGestion.postularEstudiante(rut, codigoBeca);

            if (resultado) {
                JOptionPane.showMessageDialog(
                    this,
                    "Postulación realizada correctamente.");
                txtRutPostulacion.setText("");
                txtCodigoBeca.setText("");

            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "No se encontró la beca indicada.",
                    "Postulación no realizada",
                    JOptionPane.WARNING_MESSAGE);
            }

        }catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Error numérico",
                JOptionPane.WARNING_MESSAGE);
                    
                

        } catch (EstudianteNoEncontradoException e) {

            JOptionPane.showMessageDialog(
                this,
                "No se encontró un estudiante con ese RUT.",
                "Estudiante no encontrado",
                JOptionPane.WARNING_MESSAGE);
        }
        catch (BecaNoEncontradaException e) {

            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Beca no encontrada",
                JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_btnPostularActionPerformed

    private void txtDireccionHogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionHogarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionHogarActionPerformed

    private void txtPromedioNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPromedioNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPromedioNotasActionPerformed

    private void txtDireccionEstadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionEstadiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionEstadiaActionPerformed

    private void btnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteActionPerformed
        // TODO add your handling code here:
        String rut = txtRutBuscar.getText().trim();

    Estudiante estudiante = programaGestion.buscarEstudiante(rut);

    if (estudiante == null) {

        JOptionPane.showMessageDialog(
                this,
                "No se encontró un estudiante con ese RUT.",
                "Estudiante no encontrado",
                JOptionPane.WARNING_MESSAGE
        );

        txtAreaEstudiante.setText("");

    } else {

        txtAreaEstudiante.setText(
                "Nombre: " + estudiante.getNombre() + "\n"
                + "Edad: " + estudiante.getEdad() + "\n"
                + "RUT: " + estudiante.getRut() + "\n"
                + "Sexo: " + estudiante.getSexo() + "\n"
                + "Dirección hogar: " + estudiante.getDireccionHogar() + "\n"
                + "Dirección estadía: " + estudiante.getDireccionEstadia() + "\n"
                + "Porcentaje RSH: " + estudiante.getPorcentajeRSH() + "\n"
                + "Nivel deportividad: " + estudiante.getNivelDeportividad() + "\n"
                + "Ingresos familiares: " + estudiante.getIngresosFamiliares() + "\n"
                + "Promedio notas: " + estudiante.getPromedioNotas()
        );
    }
    }//GEN-LAST:event_btnBuscarEstudianteActionPerformed

    private void txtRutBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void limpiarCamposRegistro() {
    txtNombre.setText("");
    txtEdad.setText("");
    txtRut.setText("");
    txtSexo.setText("");
    txtDireccionHogar.setText("");
    txtDireccionEstadia.setText("");
    txtPorcentajeRSH.setText("");
    txtNivelDeportividad.setText("");
    txtIngresosFamiliares.setText("");
    txtPromedioNotas.setText("");
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEstudiante;
    private javax.swing.JButton btnPostular;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBuscarEstudiante;
    private javax.swing.JPanel panelConsultaEstudiante;
    private javax.swing.JPanel panelPostularBeca;
    private javax.swing.JPanel panelRegistrarEstudiante;
    private javax.swing.JTabbedPane tabbedPanePrincipal;
    private javax.swing.JTextArea txtAreaEstudiante;
    private javax.swing.JTextField txtCodigoBeca;
    private javax.swing.JTextField txtDireccionEstadia;
    private javax.swing.JTextField txtDireccionHogar;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIngresosFamiliares;
    private javax.swing.JTextField txtNivelDeportividad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPorcentajeRSH;
    private javax.swing.JTextField txtPromedioNotas;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtRutBuscar;
    private javax.swing.JTextField txtRutPostulacion;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
